-
  name: UDP
#  status: /var/run/openvpn.thearrow-udp.status
  status: C:\Users\severin\Development\vpnmon\openvpn.thearrow-udp.status
  config: /etc/openvpn/thearrow-udp.conf
-
  name: TCP
#  status: /var/run/openvpn.thearrow-tcp.status
  status: C:\Users\severin\Development\vpnmon\openvpn.thearrow-tcp.status
  config: /etc/openvpn/thearrow-tcp.conf