VPNSession:
  actAs: [Timestampable]
  tableName: vpn_session
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    certificate_id: integer
    ip: string(40)
    port: integer
    time_start: timestamp
    duration: integer
    bytes_received: integer
    bytes_sent: integer
    instance_id: integer
  relations:
    Certificate:
      foreignAlias: VPNSessions
    Instance:
      foreignAlias: VPNSessions

Certificate:
  actAs: [Timestampable]
  tableName: certificate
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    cname: string(255)
    email: string(255)

Instance:
  actAs: [Timestampable]
  tableName: instance
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name: string(50)
    config_file: string(255)
    status_file: string(255)